<a href="https://colab.research.google.com/github/urvimistry1708/MachineLearning/blob/main/WhiteWineKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import math as m

In [ ]:
data=pd.read_csv("winequality-white-new.csv");
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.0              0.27         0.36  ...       0.45      8.8        6
1            6.3              0.30         0.34  ...       0.49      9.5        6
2            8.1              0.28         0.40  ...       0.44     10.1        6
3            7.2              0.23         0.32  ...       0.40      9.9        6
4            7.2              0.23         0.32  ...       0.40      9.9        6

[5 rows x 12 columns]

In [ ]:
x=data.iloc[:,0:11].values
y=data.iloc[:,11:].values
x
print(y)

[[6]
 [6]
 [6]
 ...
 [6]
 [7]
 [6]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)


In [ ]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
x_train=scale.fit_transform(x_train)
x_test=scale.transform(x_test)


In [ ]:
m.sqrt(len(y_test))

31.304951684997057

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=31,p=11,metric='euclidean')
model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=31, p=11,
                     weights='uniform')

In [ ]:

y_pred=model.predict(x_test)
y_pred

array([5, 6, 6, 7, 5, 5, 6, 6, 6, 5, 6, 7, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 5, 5, 7, 6, 5, 5, 6, 6, 6, 6, 6, 7, 7, 6, 6, 6, 6, 6,
       5, 6, 5, 7, 6, 6, 7, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6,
       5, 5, 5, 5, 6, 5, 6, 7, 6, 6, 6, 5, 5, 7, 5, 5, 6, 6, 5, 6, 6, 7,
       5, 6, 7, 6, 5, 7, 5, 6, 6, 5, 5, 7, 6, 5, 6, 6, 6, 7, 6, 6, 7, 5,
       5, 6, 6, 6, 7, 7, 5, 5, 7, 6, 5, 5, 5, 5, 6, 7, 5, 6, 6, 6, 6, 6,
       6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6,
       5, 6, 6, 5, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 7,
       6, 7, 6, 6, 5, 6, 6, 5, 7, 5, 6, 6, 5, 7, 7, 5, 5, 7, 6, 6, 7, 7,
       5, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 7, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       7, 6, 6, 6, 5, 5, 7, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 7, 5, 7, 6, 6,
       5, 6, 6, 6, 5, 5, 7, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6,
       6, 6, 5, 5, 6, 6, 7, 7, 5, 5, 6, 5, 5, 6, 5,

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[  0,   0,   6,   2,   1,   0],
       [  0,   0,  30,  20,   1,   0],
       [  0,   0, 169, 121,   5,   0],
       [  0,   0,  77, 300,  32,   0],
       [  0,   0,  11, 119,  53,   0],
       [  0,   0,   1,  21,  11,   0]])

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred)*100)

53.265306122448976
